### ISSUE TITLE
Bug when input is not a 'pure color value'

### ISSUE THREAD

**Issue by BernieHuang2008** [BernieHuang2008/variablefiy#1]
If I input the css below, the app cannot detect non-pure color value.
```css
div {
    border: solid 1px black;
}
```
That is, the value column will show as below: 
![image](https://github.com/BernieHuang2008/variablefiy/assets/88757735/53a37c1d-938f-45d6-96b7-6133cac2e5c1)

But the app is designed to extract only the color part, not all of the values!

And when I click `save`, the saved file is also unexpected:
```css
body {
    --var-div-border: solid 1px #000;
}

div {
    border: var(--var-div-border);
}
```

You see, the whole value are been replaced as variable!
